/home/mis/Bureau/roadef-code/open-wbo-conquer-master/Encoder.o /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Encoder.or /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Encoder.od /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Encoder.op: \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Encoder.cc \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Encoder.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Solver.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Heap.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Vec.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/IntTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/XAlloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alg.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/Options.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/ParseUtils.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Map.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/BoundedQueue.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Constants.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Clone.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverStats.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_CNetworks.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Encodings.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/../MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_GTE.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_Ladder.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_MTotalizer.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_SWC.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_Totalizer.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/encodings/Enc_Adder.h
/home/mis/Bureau/roadef-code/open-wbo-conquer-master/Main.o /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Main.or /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Main.od /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Main.op: /home/mis/Bureau/roadef-code/open-wbo-conquer-master/Main.cc \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/Options.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/IntTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Vec.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/XAlloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/ParseUtils.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/System.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Solver.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Heap.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alg.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Map.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/BoundedQueue.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Constants.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Clone.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverStats.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/FormulaPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserMaxSAT.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/Alg_LinearSU.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../Encoder.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_CNetworks.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Encodings.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/../MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_GTE.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_Ladder.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_MTotalizer.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_SWC.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_Totalizer.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../encodings/Enc_Adder.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../MaxSAT.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/Alg_MSU3.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/Alg_OLL.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/Alg_PartMSU3.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../MaxSAT_Partition.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../MaxSAT.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../graph/Graph.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../graph/Graph_Communities.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../graph/Graph.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/Alg_WBO.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/../MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/algorithms/Alg_Basic.h
/home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.o /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.or /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.od /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.op: /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.cc \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Solver.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Heap.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Vec.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/IntTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/XAlloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alg.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/Options.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/ParseUtils.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Map.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/BoundedQueue.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Constants.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Clone.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverStats.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/FormulaPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/System.h
/home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.o /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.or /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.od /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.op: \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.cc \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Solver.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Heap.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Vec.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/IntTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/XAlloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alg.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/Options.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/ParseUtils.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Map.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/BoundedQueue.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Constants.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Clone.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverStats.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/FormulaPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxTypes.h
/home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT_Partition.o /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT_Partition.or /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT_Partition.od /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT_Partition.op: \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT_Partition.cc \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/IntTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alg.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Vec.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/XAlloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Map.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT_Partition.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSAT.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Solver.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Heap.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/Options.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/ParseUtils.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/BoundedQueue.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Constants.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Clone.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverStats.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/FormulaPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/System.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/graph/Graph.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/graph/Graph_Communities.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/graph/Graph.h
/home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.o /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.or /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.od /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.op: \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.cc \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/ParserPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxSATFormula.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Solver.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Heap.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Vec.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/IntTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/XAlloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alg.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/Options.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/utils/ParseUtils.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverTypes.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Map.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Alloc.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/BoundedQueue.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/Constants.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/mtl/Clone.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/solvers/glucose4.1/core/SolverStats.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/FormulaPB.h \
 /home/mis/Bureau/roadef-code/open-wbo-conquer-master/MaxTypes.h
